### ISSUE TITLE
tried many times, but not work

### ISSUE THREAD

**Issue by wfraga18** [esp8266-examples/ota-basic#2]
Hi,

thanks by the manual, but i tried upload many times
( compile no error, upload by usb ok , led blinking ok )

but not enable option on arduino interface ( i restarted many times )
in serial console, don't show nothing after show the IP

what can be ?
thanks

**Comment by ramonverde** [comment]
Hi wfraga18,
please check the following steps:
- Arduino software 1.6.7 or later ir required (it will not work on earlier versions)
- ssid and password (in code) is set to your network configuration
- check the IP assigned to Arduino and verify it responds to ping
- in Arduino software: select upload using "OTA"
- do NOT enable "ArduinoOTA.setPassword()", as it's not working yet

Usually it requires a few seconds (20-30s) after the program is opened until it detects the ip configuration of the arduino (no close& restart is required).
Please, tell me if the above steps helped you.

**Comment by ramonverde** [comment]
I close the issue as there is no more doubt about how this sketch works
